drop table if exists member CASCADE;

create table member
( id bigint generated by default as identity,
  name varchar(255),
  primary key(id)
)

insert into member(name) values('David')

delete from member

https://proandroiddev.com/how-to-create-a-rest-api-for-your-app-with-spring-boot-kotlin-gradle-part-3-adding-a-h2-7f9e6219b367


http://www.h2database.com/html/main.html
chmod 755 ./h2

spring.datasource.url = jdbc:h2:tcp://localhost/~/test
spring.datasource.driver-class-name = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password =
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = none
